### ISSUE TITLE
SMILES

### ISSUE THREAD

**Issue by pythonnewbie3** [TinacciL/Isomers_generator#1]
Is it possible to export the list of molecules to a list of SMILES?

**Comment by TinacciL** [comment]
Hi,
i think once you get all the possible isomers you can read it (xyz) with Babel and export with a SMILES or using RDKIT. 
Be aware that radicals are not deal well by SMILES.
My code could not do it.

**Comment by pythonnewbie3** [comment]
Hi, 
thank's for you reply.
How do I install the IG_lib file to my environment in conda? I've tried python IG_lib.py install and conda build.
Best wishes

**Comment by TinacciL** [comment]
You just need to download the file and put in the directory in which you are working on. 
Then you can load all the function inside IG_lib with "from  IG_lib import blablabla" in your python file or you can also dowload the 
IG.ipynb file and work from it.

BR Lorenzo

**Comment by pythonnewbie3** [comment]
Thank you for your answer. I got it running. Do you have any estimations on computing Time? Is there an option to only generate let's say 200 isomers inorder to decrease the calculation time? 

And how would you like me to cite this in my masterthesis? :-)

**Comment by TinacciL** [comment]
The code is not implemented for huge number of atoms,I have never test it.
There is not way to control the number of isomers by a command, you have to put the hand on the code I think.
Be aware that the IG create all possibile isomers, meaning also really high in energy (radicals etc). 

I checked the code and all the molecules create from the IG program are molecular graph, I wrote a python function in order to transform the molecular graph to a xyz file.

```
import networkx as nx
from rdkit import Chem
def MolFromGraphs(G):
	'''
	Function that takes as input the networkx graph (each node must have an atom property H,N,C,O etc) and return the mol (rdkit) object
	the function dont discriminate between different type of bond, it care only about the connectivity
	'''
	#https://stackoverflow.com/questions/51195392/smiles-from-graph
	# extract the adjacency matrix and the list of atoms
	adjacency_matrix = nx.adjacency_matrix(G).todense().tolist()
	node_list = []
	for i,node in enumerate(G):
		node_list.append(G.nodes[i]['atom'])
	# create empty editable mol object
	mol = Chem.RWMol()
	# add atoms to mol and keep track of index
	node_to_idx = {}
	for i in range(len(node_list)):
		a = Chem.Atom(node_list[i])
		molIdx = mol.AddAtom(a)
		node_to_idx[i] = molIdx
	# add bonds between adjacent atoms
	for ix, row in enumerate(adjacency_matrix):
		for iy, bond in enumerate(row):
			# only traverse half the matrix
			if iy >= ix:
				break
			# add relevant bond type (there are many more of these)
			if bond == 0:
				continue
			else:
				bond_type = Chem.rdchem.BondType.SINGLE
				mol.AddBond(node_to_idx[ix], node_to_idx[iy], bond_type)
			#elif bond == 2:
			#    bond_type = Chem.rdchem.BondType.DOUBLE
			#    mol.AddBond(node_to_idx[ix], node_to_idx[iy], bond_type)          
	Chem.SanitizeMol(mol)
	return mol
```

I add on the Isomer generetor the "example" directory in which there is a jupyther notebook with another example (inside the mol_lib.py there is the function above) and a way in order to compute the xyz from graph via RDKit UFF.

Regarding the citation, it is enought to cite the Github project page 😉. 
Enjoy python and chemistry!
Lorenzo

**Comment by pythonnewbie3** [comment]
Thank you sooooo much it worked. :-) I'm sooo happy right now. I've been searching for a isomer generator to give me smiles for a week now!
You too enjoy python and chemistry. :-)

**Comment by pythonnewbie3** [comment]
Ok one more question: 
How do I creat a list of all the possible isomers?

from IG_lib import isomers_generator
from IG_lib import mol_graph_image
from IG_lib import create_list_graph
from mol_lib import MolFromGraphs
from rdkit import Chem
n_H = 4 # the number (int) of hydrogen atoms
n_C = 1 # the number (int) of carbon atoms
n_N = 0 # the number (int) of nitrogen atoms
n_O = 0 # the number (int) of oxygen atoms

tree = isomers_generator(n_H,n_C,n_N,n_O) 
len(tree)
g=create_list_graph(tree)
x=MolFromGraphs(g)
y=Chem.MolToSmiles(x)
print(y)

when I run this I get:
Graph' object cannot be interpreted as an integer

**Comment by TinacciL** [comment]
If you look at the at "Isomers_generator/example/tmp_mol.ipynb" there is the example and you can play with rdikit etc.

tree is a graph of graphs. 

It is enought: 
```
tree = isomers_generator(n_H,n_C,n_N,n_O)
struct = []
for i,node in enumerate(tree):
    if tree.nodes[i]['block'] == 'hydrogen':
        struct.append(tree.nodes[i]['graph'].copy())
        mol_graph_image(tree.nodes[i]['graph'].copy())#to visualize
smiles = []
for i,item in enumerate(struct):
    tmp_mol = MolFromGraphs(item)
    tmp_sml = Chem.MolToSmiles(tmp_mol)
    smiles.append(tmp_sml)
    print(tmp_sml)
```
Lorenzo

**Comment by pythonnewbie3** [comment]
Thank you. :-)

**Comment by pythonnewbie3** [comment]
I've tried C4H10 and my CPU is at 100% so I stopped because I was worried about it being fried. What computing power did you have when calculating Molecules.

**Comment by TinacciL** [comment]
I have never tested it, the code is not optimized (it was an exercise). 
It create all possbile molecules, something really high in energy. The only way i can see is to deleted some part of the code (after the H addiction the skeleton) and put some contrain in the structure if you do not want it (like  a cyclic butan functional group etc).

**Comment by pythonnewbie3** [comment]
Thank you. :-) I'll try my best.
